spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: mysql1234Z=
#    url: jdbc:mysql://home.ximouzhao.com/springboottest?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://10.2.0.38:3306/resource_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  redis:
    host: 192.168.64.128
    port: 6379
server:
  servlet:
    context-path: /api
  port: 8080
  compression:
    enabled: true
    mime-types: application/json  image/x-icon  text/plain application/x-javascript application/javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png
    min-response-size: 1024
filesdir: /opt/data/files/